# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rithesh Kumar Ravikumar 
email: ritheshrkumar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Music. DSP. Electronics.
 A musician creating technology for music. Electronics nerd.
 Will wash dishes for DSP. Can run a 5k for C++. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.linkedin.com/in/ritheshkumar" # the base hostname & protocol for your site
twitter_username: rithesh_kumar
github_username:  RitheshKumar

# Build settings
markdown: kramdown
